const mobileData = [
  {
    id: '1',
    model: 'Iphone 14 pro max',
    color: 'white',
    ram: '4',
    screen: '6.7',
    cameras: '3',
    price: '1200',
    image: 'images/1.webp',
  },
  {
    id: '2',
    model: 'Iphone 12',
    color: 'red',
    ram: '4',
    screen: '6.1',
    cameras: '3',
    price: '800',
    image: 'images/2.webp',
  },
  {
    id: '3',
    model: 'Samsung Galaxy S21',
    color: 'violet',
    ram: '8',
    screen: '6.2',
    cameras: '3',
    price: '920',
    image: 'images/3.webp',
  },
  {
    id: '4',
    model: 'Xiaomi Mi 10T',
    color: 'grey',
    ram: '6',
    screen: '6.67',
    cameras: '4',
    price: '420',
    image: 'images/4.webp',
  },
  {
    id: '5',
    model: 'Xiaomi Redmi Note 11',
    color: 'blue',
    ram: '4',
    screen: '6.43',
    cameras: '4',
    price: '400',
    image: 'images/5.webp',
  },
  {
    id: '6',
    model: 'Iphone 12',
    color: 'violet',
    ram: '4',
    screen: '6.1',
    cameras: '3',
    price: '800',
    image: 'images/6.webp',
  },
  {
    id: '7',
    model: 'Samsung Galaxy A33',
    color: 'white',
    ram: '6',
    screen: '6.4',
    cameras: '4',
    price: '350',
    image: 'images/7.webp',
  },
  {
    id: '8',
    model: 'OPPO Find X5 Pro',
    color: 'black',
    ram: '12',
    screen: '6.7',
    cameras: '2',
    price: '740',
    image: 'images/8.webp',
  },
  {
    id: '9',
    model: 'Oppo A54',
    color: 'grey',
    ram: '6',
    screen: '6.49',
    cameras: '3',
    price: '650',
    image: 'images/9.webp',
  },
  {
    id: '10',
    model: 'Oppo Find X3 Neo',
    color: 'black',
    ram: '12',
    screen: '6.55',
    cameras: '3',
    price: '700',
    image: 'images/10.webp',
  },
];

export default mobileData;
